services:
  - type: web
    name: records-app-v2
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: APP_SECRET
        generateValue: true
      - key: COOKIE_SECURE
        value: "1"
      - key: DATABASE_PATH
        value: /var/data/data.db
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
